import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import initTranslations from "../i18n";
import TranslationsProvider from "@/components/Providers/TranslationsProvider";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import { AlertContextProvider } from "@/contexts/AlertContext";
import { Modal } from "@/components/common/Modal";
import CommonContextProvider from "@/contexts/CommonContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const i18nNamespaces = ['admin', 'appointments', 'auth', 'calendar', 'common', 'companies', 'coordinator', 'dashboard', 'directors', 'goals', 'locations', 'managers', 'promotors', 'sales', 'sellers', 'settings'];
export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>) {
  const { resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <html lang="en">
      <body className={inter.className}>
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}
        >
          <AlertContextProvider>
            <CommonContextProvider>
              <Modal />
              <ToastContainer />
              {children}
            </CommonContextProvider>
          </AlertContextProvider>
        </TranslationsProvider>
      </body>
    </html>
  );
}
